---
- name: Destroy AWS S3 Bucket with Terraform
  hosts: all
  become: false
  tasks:
    - name: Run Terraform Destroy
      ansible.builtin.command:
        cmd: terraform destroy -auto-approve
        chdir: ~/terraform-aws-s3
