---
- name: Install LAMP Stack on Ubuntu 18.04
  hosts: webserver
  become: yes
  tasks:

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL is running and enabled on boot
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Secure MySQL Installation
      mysql_secure_installation:
        login_user: root
        login_password: ""
        new_password: "your_password_here"
        password_auth: yes
        remove_anonymous_user: yes
        disallow_root_login_remotely: yes
        remove_test_db: yes
        state: present

    - name: Install PHP and required extensions
      apt:
        name: 
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-curl
          - php-json
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
        state: present

    - name: Restart Apache to apply PHP configuration
      service:
        name: apache2
        state: restarted

    - name: Create a PHP info file
      copy:
        dest: /var/www/html/info.php
        content: "<?php phpinfo(); ?>"
        mode: '0644'

    - name: Set MySQL root password environment variable
      lineinfile:
        dest: /root/.my.cnf
        line: 'password=your_password_here'
        create: yes

